export const environment = {
  production: true,
  baseUrl: 'http://41.218.83.178:6002/',
  endPoints: {
    login: 'api/user/authenticate',
    getDashboard: 'api/user/get/dashboard',
    getParentCategory: 'api/category/list/parent',
    getChildCategory: 'api/category/list/child/',
    getOrderList: 'api/order/list/user/',
    getOrderListByProvince: 'api/order/list/province/',
    getOrderListForSalesman: 'api/order/list/associated/user/',
    getAllOrderList: 'api/order/list/',
    getProductList: 'api/product/list/category/',
    searchProductInParentCategory: 'api/product/search/parentCategory/',
    submitOrder: 'api/order/',
    createPayment: 'api/user/create/payment',
    getPaymentHistory: 'api/user/payment/history',
    getPaymentHistoryForSm: 'api/user/list/payments/SM',
    getOrderDetail: 'api/order/detail/',
    changeOrderStatus: 'api/order/status/',
    addCategories: 'api/category',
    getCustomerListBySalesman: 'api/user/list/associated/customer',
    getAllCustomerList: 'api/user/list/all/customer',
    getCustomerListByAdmin: 'api/user/list/customer',
    getCustomerListByProvince: 'api/user/list/by/province/customer',
    getAllSalesmanList: 'api/user/list/all/salesman',
    changePassword: 'api/user/changePassword',
    updateUser: 'api/user/update/user',
    resetPassword: 'api/user/resetPassword/',
    getCustomerStatement: 'api/user/customer/statements',
    getTkProduct: 'a pi/product/list/tk/products',
    addCompProduct: 'api/product/add/comp/product',
    appTkProduct: 'api/product/add/tk/product',
    appProduct: 'api/product',
    getUnitSizeList: 'api/product/list/unitsize',
    getCaptureProductList: 'api/product/list/unitsize/products',
    captureProduct: 'api/order/capture/price',
    createOrderToErp: 'api/erp/createOrderToERP',
    createEditOrderToErp: 'api/erp/createEditedOrderToERP',
    updateProduct: 'api/product/update',
    getPriceExecutiveDashboardData: 'api/user/priceExecutive/dashboard',
    getPendingInvoiceData: 'api/user/customer/pendinginvoice'
  },
  storageKeys: {}
};
